# Data Munging
- 用pandas进行数据加载和预处理
    - Fast and easy data loading
    - Dealing with problematic data
    - Dealing with big datasets
    - 访问其他数据格式
    - Data preprocessing
    - Data 选择
- Working with categorical and textual data
- A special type of data: text
- Scraping the Web
- Creating NumPy arrays
    - From lists to unidimensional arrays
    - Controlling the memory size
    - Heterogeneous lists
    - From lists to multidimensional arrays
    - Resizing arrays
    - Arrays derived from NumPy functions
    - Getting an array directly from a file
    - Extracting data from pandas
- NumPy fast operation and computations
    - Matrix operations
- Slicing and indexing with NumPy arrays
    - Stacking NumPy arrays

## 用pandas进行数据加载和预处理

### Fast and easy data loading

In [9]:
import pandas as pd
iris_filename = 'datasets-uci-iris.csv'
iris = pd.read_csv(iris_filename, sep=',', decimal='.', header=None,
names= ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target'])

In [10]:
# If the dataset is available online, 
# and you can follow these steps to
# download it from the Internet:
import urllib
url = "http://aima.cs.berkeley.edu/data/iris.csv"
set1 = urllib.request.Request(url)
iris_p = urllib.request.urlopen(set1)
iris_other = pd.read_csv(iris_p, sep=',', decimal='.',
header=None, names= ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target'])
iris_other.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width       target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
iris.tail()

sepal_length  sepal_width  petal_length  petal_width          target
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [5]:
iris.head(2)

sepal_length  sepal_width  petal_length  petal_width       target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa

In [5]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target'], dtype='object')

In [6]:
Y = iris['target']
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: target, Length: 150, dtype: object

In [7]:
X = iris[['sepal_length', 'sepal_width']]
X

sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [11]:
X.shape

(150, 2)

In [12]:
Y.shape

(150,)

### Dealing with problematic data

In [13]:
import pandas as pd
fake_dataset = pd.read_csv('a_loading_example_1.csv', sep=',')
fake_dataset

Date  Temperature_city_1  Temperature_city_2  Temperature_city_3  \
0  20140910                80.0                32.0                  40   
1  20140911               100.0                50.0                  36   
2  20140912               102.0                55.0                  46   
3  20140913                60.0                20.0                  35   
4  20140914                60.0                 NaN                  32   
5  20140915                 NaN                57.0                  42   

   Which_destination  
0                  1  
1                  2  
2                  1  
3                  3  
4                  3  
5                  2

In [15]:
fake_dataset = pd.read_csv('a_loading_example_1.csv', parse_dates=[0])
fake_dataset

Date  Temperature_city_1  Temperature_city_2  Temperature_city_3  \
0 2014-09-10                80.0                32.0                  40   
1 2014-09-11               100.0                50.0                  36   
2 2014-09-12               102.0                55.0                  46   
3 2014-09-13                60.0                20.0                  35   
4 2014-09-14                60.0                 NaN                  32   
5 2014-09-15                 NaN                57.0                  42   

   Which_destination  
0                  1  
1                  2  
2                  1  
3                  3  
4                  3  
5                  2

In [16]:
fake_dataset.fillna(50)

Date  Temperature_city_1  Temperature_city_2  Temperature_city_3  \
0 2014-09-10                80.0                32.0                  40   
1 2014-09-11               100.0                50.0                  36   
2 2014-09-12               102.0                55.0                  46   
3 2014-09-13                60.0                20.0                  35   
4 2014-09-14                60.0                50.0                  32   
5 2014-09-15                50.0                57.0                  42   

   Which_destination  
0                  1  
1                  2  
2                  1  
3                  3  
4                  3  
5                  2

In [17]:
fake_dataset.fillna(-1)

Date  Temperature_city_1  Temperature_city_2  Temperature_city_3  \
0 2014-09-10                80.0                32.0                  40   
1 2014-09-11               100.0                50.0                  36   
2 2014-09-12               102.0                55.0                  46   
3 2014-09-13                60.0                20.0                  35   
4 2014-09-14                60.0                -1.0                  32   
5 2014-09-15                -1.0                57.0                  42   

   Which_destination  
0                  1  
1                  2  
2                  1  
3                  3  
4                  3  
5                  2

In [18]:
fake_dataset.fillna(fake_dataset.mean(axis=0))

Date  Temperature_city_1  Temperature_city_2  Temperature_city_3  \
0 2014-09-10                80.0                32.0                  40   
1 2014-09-11               100.0                50.0                  36   
2 2014-09-12               102.0                55.0                  46   
3 2014-09-13                60.0                20.0                  35   
4 2014-09-14                60.0                42.8                  32   
5 2014-09-15                80.4                57.0                  42   

   Which_destination  
0                  1  
1                  2  
2                  1  
3                  3  
4                  3  
5                  2

In [19]:
bad_dataset = pd.read_csv('a_loading_example_2.csv', error_bad_lines=False)

b'Skipping line 4: expected 3 fields, saw 4\n'


In [20]:
bad_dataset

Val1  Val2  Val3
0     0     0     0
1     1     1     1
2     3     3     3

### Dealing with big datasets

In [41]:
import pandas as pd
iris_chunks = pd.read_csv(iris_filename, header=None, names=['C1', 'C2', 'C3', 'C4', 'C5'], chunksize=10)
for chunk in iris_chunks:
    print ('Shape:', chunk.shape)
#     print (chunk,'\n')

Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)
Shape: (10, 5)


In [24]:
iris_iterator = pd.read_csv(iris_filename, header=None, names=['C1', 'C2', 'C3', 'C4', 'C5'], iterator=True)

In [25]:
iris_iterator.get_chunk(10).shape

(10, 5)

In [27]:
iris_iterator.get_chunk(20).shape

(20, 5)

In [28]:
piece = iris_iterator.get_chunk(2)
piece

C1   C2   C3   C4               C5
50  7.0  3.2  4.7  1.4  Iris-versicolor
51  6.4  3.2  4.5  1.5  Iris-versicolor

In [42]:
import csv

fieldnames= ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target']
with open(iris_filename, 'rt') as data_stream:
    # 'rt' mode
    for n, row in enumerate(csv.DictReader(data_stream, fieldnames = fieldnames, dialect='excel')):
            if n== 0:
                print (n,row)
            else:
                break

0 OrderedDict([('sepal_length', '5.1'), ('sepal_width', '3.5'), ('petal_length', '1.4'), ('petal_width', '0.2'), ('target', 'Iris-setosa')])


In [43]:
with open(iris_filename, 'rt') as data_stream:
    for n, row in enumerate(csv.reader(data_stream, dialect='excel')):
            if n==0:
                print (row)
            else:
                break

['5.1', '3.5', '1.4', '0.2', 'Iris-setosa']


In [31]:
def batch_read(filename, batch=5):
    # open the data stream
    with open(filename, 'rt') as data_stream:
        # reset the batch
        batch_output = list()
        # iterate over the file
        for n, row in enumerate(csv.reader(data_stream, dialect='excel')):
            # if the batch is of the right size
            if n > 0 and n % batch == 0:
                # yield back the batch as an ndarray
                yield(np.array(batch_output))
                # reset the batch and restart
                batch_output = list()
            # otherwise add the row to the batch
            batch_output.append(row)
        # when the loop is over, yield what's left
        yield(np.array(batch_output))

In [32]:
import numpy as np
for batch_input in batch_read(iris_filename, batch=3):
    print (batch_input)
    break

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']]


### 访问其他数据格式

In [35]:
import pandas as pd
my_own_dataset = pd.DataFrame({'Col1': range(5), 'Col2': [1.0]*5, 'Col3': 1.0, 'Col4': 'Hello World!'})
my_own_dataset

Col1  Col2  Col3          Col4
0     0   1.0   1.0  Hello World!
1     1   1.0   1.0  Hello World!
2     2   1.0   1.0  Hello World!
3     3   1.0   1.0  Hello World!
4     4   1.0   1.0  Hello World!

In [36]:
my_wrong_own_dataset = pd.DataFrame({'Col1': range(5), 'Col2': 'string', 'Col3': range(2)})

ValueError: arrays must all be same length

In [37]:
my_own_dataset.dtypes

Col1      int64
Col2    float64
Col3    float64
Col4     object
dtype: object

In [38]:
my_own_dataset['Col1'] = my_own_dataset['Col1'].astype(float)
my_own_dataset.dtypes

Col1    float64
Col2    float64
Col3    float64
Col4     object
dtype: object

### Data preprocessing

In [39]:
mask_feature = iris['sepal_length'] > 6.0
mask_feature

0      False
1      False
2      False
3      False
4      False
       ...  
145     True
146     True
147     True
148     True
149    False
Name: sepal_length, Length: 150, dtype: bool

In [32]:
mask_target = iris['target'] == 'Iris-virginica'

In [33]:
iris.loc[mask_target, 'target'] = 'New label'

In [34]:
iris['target'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'New label'], dtype=object)

In [35]:
grouped_targets_mean = iris.groupby(['target']).mean()
grouped_targets_mean

sepal_length  sepal_width  petal_length  petal_width
target                                                               
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
New label               6.588        2.974         5.552        2.026

In [36]:
grouped_targets_var = iris.groupby(['target']).var()
grouped_targets_var

sepal_length  sepal_width  petal_length  petal_width
target                                                               
Iris-setosa          0.124249     0.145180      0.030106     0.011494
Iris-versicolor      0.266433     0.098469      0.220816     0.039106
New label            0.404343     0.104004      0.304588     0.075433

In [37]:
iris.sort_values(by='sepal_length').head()

sepal_length  sepal_width  petal_length  petal_width       target
13           4.3          3.0           1.1          0.1  Iris-setosa
42           4.4          3.2           1.3          0.2  Iris-setosa
38           4.4          3.0           1.3          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
41           4.5          2.3           1.3          0.3  Iris-setosa

In [38]:
# This is just an example, with no time_series data
# smooth_time_series = pd.rolling_mean(time_series, 5)

In [39]:
# This is just an example, with no time_series data
# median_time_series = pd.rolling_median(time_series, 5)

In [40]:
iris.apply(np.count_nonzero, axis=1).head()

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [41]:
iris.apply(np.count_nonzero, axis=0)

sepal_length    150
sepal_width     150
petal_length    150
petal_width     150
target          150
dtype: int64

In [42]:
iris.applymap(lambda el:len(str(el))).head()

sepal_length  sepal_width  petal_length  petal_width  target
0             3            3             3            3      11
1             3            3             3            3      11
2             3            3             3            3      11
3             3            3             3            3      11
4             3            3             3            3      11

### Data 选择

In [43]:
import pandas as pd
dataset = pd.read_csv('a_selection_example_1.csv')
dataset

n  val1  val2 val3
0  100    10    10    C
1  101    10    20    C
2  102    10    30    B
3  103    10    40    B
4  104    10    50    A

In [44]:
dataset = pd.read_csv('a_selection_example_1.csv', index_col=0)
dataset

val1  val2 val3
n                   
100    10    10    C
101    10    20    C
102    10    30    B
103    10    40    B
104    10    50    A

In [45]:
dataset['val3'][104]

'A'

In [46]:
dataset.loc[104, 'val3']

'A'

In [47]:
dataset.ix[104, 'val3']

'A'

In [48]:
dataset.ix[104, 2]

'A'

In [49]:
dataset.iloc[4, 2]

'A'

In [50]:
dataset[['val3', 'val2']][0:2]

val3  val2
n             
100    C    10
101    C    20

In [51]:
dataset.loc[range(100, 102), ['val3', 'val2']]

val3  val2
n             
100    C    10
101    C    20

In [52]:
dataset.ix[range(100, 102), ['val3', 'val2']]

val3  val2
n             
100    C    10
101    C    20

In [53]:
dataset.ix[range(100, 102), [2, 1]]

val3  val2
n             
100    C    10
101    C    20

In [54]:
dataset.iloc[range(2), [2,1]]

val3  val2
n             
100    C    10
101    C    20

## Working with categorical and textual data

In [55]:
import pandas as pd
categorical_feature = pd.Series(['sunny', 'cloudy', 'snowy',
'rainy', 'foggy'])
mapping = pd.get_dummies(categorical_feature)
mapping

cloudy  foggy  rainy  snowy  sunny
0     0.0    0.0    0.0    0.0    1.0
1     1.0    0.0    0.0    0.0    0.0
2     0.0    0.0    0.0    1.0    0.0
3     0.0    0.0    1.0    0.0    0.0
4     0.0    1.0    0.0    0.0    0.0

In [56]:
mapping['sunny']

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: sunny, dtype: float64

In [57]:
mapping['cloudy']

0    0.0
1    1.0
2    0.0
3    0.0
4    0.0
Name: cloudy, dtype: float64

In [58]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ohe = OneHotEncoder()
levels = ['sunny', 'cloudy', 'snowy', 'rainy', 'foggy']
fit_levs = le.fit_transform(levels)
ohe.fit([[fit_levs[0]], [fit_levs[1]], [fit_levs[2]], [fit_levs[3]],
[fit_levs[4]]])
print (ohe.transform([le.transform(['sunny'])]).toarray())
print (ohe.transform([le.transform(['cloudy'])]).toarray())

[[ 0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.  0.]]


## A special type of data: text

In [59]:
from sklearn.datasets import fetch_20newsgroups
categories = ['sci.med', 'sci.space']
twenty_sci_news = fetch_20newsgroups(categories=categories)

In [60]:
print(twenty_sci_news.data[0])

From: flb@flb.optiplan.fi ("F.Baube[tm]")
Subject: Vandalizing the sky
X-Added: Forwarded by Space Digest
Organization: [via International Space University]
Original-Sender: isu@VACATION.VENARI.CS.CMU.EDU
Distribution: sci
Lines: 12

From: "Phil G. Fraering" <pgf@srl03.cacs.usl.edu>
> 
> Finally: this isn't the Bronze Age, [..]
> please try to remember that there are more human activities than
> those practiced by the Warrior Caste, the Farming Caste, and the
> Priesthood.

Right, the Profiting Caste is blessed by God, and may 
 freely blare its presence in the evening twilight ..

-- 
* Fred Baube (tm)



In [61]:
twenty_sci_news.filenames

array([ '/Users/albertoboschetti/scikit_learn_data/20news_home/20news-bydate-train/sci.space/61116',
       '/Users/albertoboschetti/scikit_learn_data/20news_home/20news-bydate-train/sci.med/58122',
       '/Users/albertoboschetti/scikit_learn_data/20news_home/20news-bydate-train/sci.med/58903',
       ...,
       '/Users/albertoboschetti/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60774',
       '/Users/albertoboschetti/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60954',
       '/Users/albertoboschetti/scikit_learn_data/20news_home/20news-bydate-train/sci.med/58911'], 
      dtype='<U104')

In [62]:
print (twenty_sci_news.target[0])
print (twenty_sci_news.target_names[twenty_sci_news.target[0]])

1
sci.space


In [63]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
word_count = count_vect.fit_transform(twenty_sci_news.data)
word_count.shape

(1187, 25638)

In [64]:
print (word_count[0])

  (0, 10827)	2
  (0, 10501)	2
  (0, 17170)	1
  (0, 10341)	1
  (0, 4762)	2
  (0, 23381)	2
  (0, 22345)	1
  (0, 24461)	1
  (0, 23137)	7
  (0, 21382)	1
  (0, 3233)	1
  (0, 10713)	1
  (0, 5650)	3
  (0, 21686)	2
  (0, 8438)	1
  (0, 17217)	1
  (0, 24626)	1
  (0, 13158)	1
  (0, 24151)	1
  (0, 17235)	1
  (0, 20909)	1
  (0, 13359)	1
  (0, 24415)	1
  (0, 24547)	1
  (0, 7646)	1
  :	:
  (0, 15968)	1
  (0, 12362)	1
  (0, 3191)	1
  (0, 23129)	1
  (0, 23241)	1
  (0, 18474)	1
  (0, 24930)	1
  (0, 6017)	3
  (0, 10188)	1
  (0, 3808)	2
  (0, 18642)	1
  (0, 20110)	1
  (0, 18744)	1
  (0, 13318)	1
  (0, 5148)	1
  (0, 11330)	1
  (0, 15246)	1
  (0, 10785)	1
  (0, 5134)	1
  (0, 13384)	1
  (0, 18586)	1
  (0, 12716)	1
  (0, 9796)	1
  (0, 23849)	1
  (0, 10778)	1


In [65]:
word_list = count_vect.get_feature_names()
for n in word_count[0].indices:
    print ('Word "%s" appears %i times' % (word_list[n], word_count[0, n]))

Word "from" appears 2 times
Word "flb" appears 2 times
Word "optiplan" appears 1 times
Word "fi" appears 1 times
Word "baube" appears 2 times
Word "tm" appears 2 times
Word "subject" appears 1 times
Word "vandalizing" appears 1 times
Word "the" appears 7 times
Word "sky" appears 1 times
Word "added" appears 1 times
Word "forwarded" appears 1 times
Word "by" appears 3 times
Word "space" appears 2 times
Word "digest" appears 1 times
Word "organization" appears 1 times
Word "via" appears 1 times
Word "international" appears 1 times
Word "university" appears 1 times
Word "original" appears 1 times
Word "sender" appears 1 times
Word "isu" appears 1 times
Word "vacation" appears 1 times
Word "venari" appears 1 times
Word "cs" appears 1 times
Word "cmu" appears 1 times
Word "edu" appears 2 times
Word "distribution" appears 1 times
Word "sci" appears 1 times
Word "lines" appears 1 times
Word "12" appears 1 times
Word "phil" appears 1 times
Word "fraering" appears 1 times
Word "pgf" appears 1 t

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_vect = TfidfVectorizer(use_idf=False, norm='l1')
word_freq = tf_vect.fit_transform(twenty_sci_news.data)
word_list = tf_vect.get_feature_names()
for n in word_freq[0].indices:
    print ('Word "%s" has frequency %0.3f' % (word_list[n], word_freq[0, n]))

Word "from" has frequency 0.022
Word "flb" has frequency 0.022
Word "optiplan" has frequency 0.011
Word "fi" has frequency 0.011
Word "baube" has frequency 0.022
Word "tm" has frequency 0.022
Word "subject" has frequency 0.011
Word "vandalizing" has frequency 0.011
Word "the" has frequency 0.077
Word "sky" has frequency 0.011
Word "added" has frequency 0.011
Word "forwarded" has frequency 0.011
Word "by" has frequency 0.033
Word "space" has frequency 0.022
Word "digest" has frequency 0.011
Word "organization" has frequency 0.011
Word "via" has frequency 0.011
Word "international" has frequency 0.011
Word "university" has frequency 0.011
Word "original" has frequency 0.011
Word "sender" has frequency 0.011
Word "isu" has frequency 0.011
Word "vacation" has frequency 0.011
Word "venari" has frequency 0.011
Word "cs" has frequency 0.011
Word "cmu" has frequency 0.011
Word "edu" has frequency 0.022
Word "distribution" has frequency 0.011
Word "sci" has frequency 0.011
Word "lines" has freq

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer() # Default: use_idf=True
word_tfidf = tfidf_vect.fit_transform(twenty_sci_news.data)
word_list = tfidf_vect.get_feature_names()
for n in word_tfidf[0].indices:
    print ('Word "%s" has tf-idf %0.3f' % (word_list[n], word_tfidf[0, n]))

Word "fred" has tf-idf 0.089
Word "twilight" has tf-idf 0.139
Word "evening" has tf-idf 0.113
Word "in" has tf-idf 0.024
Word "presence" has tf-idf 0.119
Word "its" has tf-idf 0.061
Word "blare" has tf-idf 0.150
Word "freely" has tf-idf 0.119
Word "may" has tf-idf 0.054
Word "god" has tf-idf 0.119
Word "blessed" has tf-idf 0.150
Word "is" has tf-idf 0.026
Word "profiting" has tf-idf 0.150
Word "right" has tf-idf 0.068
Word "priesthood" has tf-idf 0.144
Word "and" has tf-idf 0.049
Word "farming" has tf-idf 0.144
Word "caste" has tf-idf 0.433
Word "warrior" has tf-idf 0.144
Word "practiced" has tf-idf 0.132
Word "those" has tf-idf 0.060
Word "than" has tf-idf 0.052
Word "activities" has tf-idf 0.091
Word "human" has tf-idf 0.084
Word "more" has tf-idf 0.046
Word "are" has tf-idf 0.035
Word "there" has tf-idf 0.039
Word "that" has tf-idf 0.027
Word "remember" has tf-idf 0.077
Word "to" has tf-idf 0.023
Word "try" has tf-idf 0.073
Word "please" has tf-idf 0.071
Word "age" has tf-idf 0.092


In [68]:
text_1 = 'we love data science'
text_2 = 'data science is hard'
documents = [text_1, text_2]
documents

['we love data science', 'data science is hard']

In [69]:
# That is what we say above, the default one
count_vect_1_grams = CountVectorizer(ngram_range=(1, 1),
stop_words=[], min_df=1)
word_count = count_vect_1_grams.fit_transform(documents)
word_list = count_vect_1_grams.get_feature_names()
print ("Word list = ", word_list)
print ("text_1 is described with", [word_list[n] + "(" +
str(word_count[0, n]) + ")" for n in word_count[0].indices])

Word list =  ['data', 'hard', 'is', 'love', 'science', 'we']
text_1 is described with ['we(1)', 'love(1)', 'data(1)', 'science(1)']


In [70]:
# Now a bi-gram count vectorizer
count_vect_1_grams = CountVectorizer(ngram_range=(2, 2))
word_count = count_vect_1_grams.fit_transform(documents)
word_list = count_vect_1_grams.get_feature_names()
print ("Word list = ", word_list)
print ("text_1 is described with", [word_list[n] + "(" +
str(word_count[0, n]) + ")" for n in word_count[0].indices])

Word list =  ['data science', 'is hard', 'love data', 'science is', 'we love']
text_1 is described with ['we love(1)', 'love data(1)', 'data science(1)']


In [71]:
# Now a uni- and bi-gram count vectorizer
count_vect_1_grams = CountVectorizer(ngram_range=(1, 2))
word_count = count_vect_1_grams.fit_transform(documents)
word_list = count_vect_1_grams.get_feature_names()
print ("Word list = ", word_list)
print ("text_1 is described with", [word_list[n] + "(" +
str(word_count[0, n]) + ")" for n in word_count[0].indices])

Word list =  ['data', 'data science', 'hard', 'is', 'is hard', 'love', 'love data', 'science', 'science is', 'we', 'we love']
text_1 is described with ['we(1)', 'love(1)', 'data(1)', 'science(1)', 'we love(1)', 'love data(1)', 'data science(1)']


In [72]:
from sklearn.feature_extraction.text import HashingVectorizer
hash_vect = HashingVectorizer(n_features=1000)
word_hashed = hash_vect.fit_transform(twenty_sci_news.data)
word_hashed.shape

(1187, 1000)

## Scraping the Web

In [73]:
import urllib.request

url = 'https://en.wikipedia.org/wiki/William_Shakespeare'
request = urllib.request.Request(url)
response = urllib.request.urlopen(request)

In [74]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response, 'html.parser')

In [75]:
soup.title

<title>William Shakespeare - Wikipedia, the free encyclopedia</title>

In [76]:
section = soup.find_all(id='mw-normal-catlinks')[0]
for catlink in section.find_all("a")[1:]:
    print(catlink.get("title"), "->", catlink.get("href"))

Category:William Shakespeare -> /wiki/Category:William_Shakespeare
Category:1564 births -> /wiki/Category:1564_births
Category:1616 deaths -> /wiki/Category:1616_deaths
Category:16th-century English male actors -> /wiki/Category:16th-century_English_male_actors
Category:English male stage actors -> /wiki/Category:English_male_stage_actors
Category:16th-century English writers -> /wiki/Category:16th-century_English_writers
Category:17th-century English writers -> /wiki/Category:17th-century_English_writers
Category:16th-century dramatists and playwrights -> /wiki/Category:16th-century_dramatists_and_playwrights
Category:17th-century dramatists and playwrights -> /wiki/Category:17th-century_dramatists_and_playwrights
Category:16th-century English poets -> /wiki/Category:16th-century_English_poets
Category:Burials in Warwickshire -> /wiki/Category:Burials_in_Warwickshire
Category:English dramatists and playwrights -> /wiki/Category:English_dramatists_and_playwrights
Category:17th-century 

## Creating NumPy arrays

### From lists to unidimensional arrays

In [77]:
import numpy as np
# Transform a list into a uni-dimensional array
list_of_ints = [1,2,3]
Array_1 = np.array(list_of_ints)
Array_1

array([1, 2, 3])

In [78]:
Array_1[1] # let's output the second value

2

In [79]:
type(Array_1)

numpy.ndarray

In [80]:
Array_1.dtype # Note: The default dtype depends on the system you're operating.

dtype('int64')

### Controlling the memory size

In [81]:
import numpy as np
Array_1.nbytes # Please note that on 64bit platforms the result will be 24.

24

In [82]:
Array_1 = np.array(list_of_ints, dtype= 'int8')

In [83]:
Array_1b = Array_1.astype('float32')
Array_1b

array([ 1.,  2.,  3.], dtype=float32)

### Heterogeneous lists

In [84]:
import numpy as np
complex_list = [1,2,3] + [1.,2.,3.] + ['a','b','c']
Array_2 = np.array(complex_list[:3]) # at first the input list is just ints
print ('complex_list[:3]', Array_2.dtype)
Array_2 = np.array(complex_list[:6]) # then it is ints and floats
print ('complex_list[:6]', Array_2.dtype)
Array_2 = np.array(complex_list) # finally we add strings
print ('complex_list[:] ',Array_2.dtype)

complex_list[:3] int64
complex_list[:6] float64
complex_list[:]  <U32


In [85]:
# Check if a NumPy array is of the desired numeric type
print (isinstance(Array_2[0],np.number))

False


### From lists to multidimensional arrays

In [86]:
import numpy as np
# Transform a list into a bidimensional array
a_list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
Array_2D = np.array(a_list_of_lists )
Array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
Array_2D[1,1]

5

In [88]:
# Transform a list into a multi-dimensional array
a_list_of_lists_of_lists = [[[1,2],[3,4],[5,6]],
[[7,8],[9,10],[11,12]]]
Array_3D = np.array(a_list_of_lists_of_lists)
Array_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [89]:
Array_3D[0,2,0] # Accessing the 5th element

5

In [90]:
np.array(list({1:2,3:4,5:6}.items()))
# http://stackoverflow.com/questions/17695456/why-python-3-needs-wrap-dict-items-with-list
# https://docs.python.org/3.3/library/stdtypes.html#dict-views

array([[1, 2],
       [3, 4],
       [5, 6]])

### Resizing arrays

In [91]:
import numpy as np
# Restructuring a NumPy array shape
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
Array_a = original_array.reshape(4,2)
Array_b = original_array.reshape(4,2).copy()
Array_c = original_array.reshape(2,2,2)
# Attention because reshape creates just views, not copies
original_array[0] = -1

In [92]:
Array_a

array([[-1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [93]:
Array_c

array([[[-1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]]])

In [94]:
Array_b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [95]:
original_array.resize(4,2)
original_array

array([[-1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [96]:
original_array.shape = (4,2)

In [97]:
original_array

array([[-1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

### Arrays derived from NumPy functions

In [98]:
import numpy as np
ordinal_values = np.arange(9).reshape(3,3)
ordinal_values

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
np.arange(9)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [100]:
np.random.randint(low=1,high=10,size=(3,3)).reshape(3,3)
# randomly generated, you can obtain a different array!

array([[6, 8, 7],
       [5, 1, 6],
       [9, 7, 3]])

In [101]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [102]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [103]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [104]:
fractions = np.linspace(start=0, stop=1, num=10)
fractions

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [105]:
growth = np.logspace(start=0, stop=1, num=10, base=10.0)
growth

array([  1.        ,   1.29154967,   1.66810054,   2.15443469,
         2.7825594 ,   3.59381366,   4.64158883,   5.9948425 ,
         7.74263683,  10.        ])

In [106]:
std_gaussian = np.random.normal(size=(3,3))
std_gaussian
# randomly generated, you can obtain a different array!

array([[-1.18035881, -0.37632937,  0.00800547],
       [ 1.24898242, -0.92410685,  0.03292396],
       [-0.17619901,  1.10657852, -0.07862104]])

In [107]:
gaussian = np.random.normal(loc=1.0, scale= 3.0, size=(3,3))
gaussian
# randomly generated, you can obtain a different array!

array([[-0.37532441,  4.00680118,  3.86295364],
       [ 6.57138005, -0.41579563,  1.95635974],
       [ 2.80182265, -2.15492916, -0.73519315]])

In [108]:
rand = np.random.uniform(low=0.0, high=1.0, size=(3,3))
# randomly generated, you can obtain a different array!

### Getting an array directly from a file

In [109]:
import numpy as np
housing = np.loadtxt('regression-datasets-housing.csv',delimiter=',', dtype=float)

In [110]:
np.loadtxt('datasets-uci-iris.csv',delimiter=',',dtype=float)

ValueError: could not convert string to float: b'Iris-setosa'

### Extracting data from pandas

In [111]:
import pandas as pd
import numpy as np
housing_filename = 'regression-datasets-housing.csv'
housing = pd.read_csv(housing_filename, header=None)

In [112]:
housing_array = housing.values
housing_array.dtype

dtype('float64')

In [113]:
housing.dtypes

0     float64
1       int64
2     float64
3       int64
4     float64
5     float64
6     float64
7     float64
8       int64
9       int64
10      int64
11    float64
12    float64
13    float64
dtype: object

## NumPy fast operation and computations

In [114]:
import numpy as np
a = np.arange(5).reshape(1,5)
a += 1
a*a

array([[ 1,  4,  9, 16, 25]])

In [115]:
a = np.arange(5).reshape(1,5) + 1
b = np.arange(5).reshape(5,1) + 1
a * b

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [116]:
a2 = np.array([1,2,3,4,5] * 5).reshape(5,5)
b2 = a2.T
a2 * b2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [117]:
print (a2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [118]:
np.sum(a2, axis=0)

array([ 5, 10, 15, 20, 25])

In [119]:
np.sum(a2, axis=1)

array([15, 15, 15, 15, 15])

In [120]:
%timeit -n 1 -r 3 [i+1.0 for i in range(10**6)]
%timeit -n 1 -r 3 np.arange(10**6)+1.0

1 loop, best of 3: 146 ms per loop
1 loop, best of 3: 5.79 ms per loop


In [121]:
import math
%timeit -n 1 -r 3 [math.sqrt(i) for i in range(10**6)]

1 loop, best of 3: 221 ms per loop


In [122]:
%timeit -n 1 -r 3 np.sqrt(np.arange(10**6))

1 loop, best of 3: 8.35 ms per loop


### Matrix operations

In [123]:
import numpy as np
M = np.arange(5*5, dtype=float).reshape(5,5)
M

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.]])

In [124]:
coefs = np.array([1., 0.5, 0.5, 0.5, 0.5])
coefs_matrix = np.column_stack((coefs,coefs[::-1]))
print (coefs_matrix)

[[ 1.   0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  1. ]]


In [125]:
np.dot(M,coefs)

array([  5.,  20.,  35.,  50.,  65.])

In [126]:
np.dot(coefs,M)

array([ 25.,  28.,  31.,  34.,  37.])

In [127]:
np.dot(M,coefs_matrix)

array([[  5.,   7.],
       [ 20.,  22.],
       [ 35.,  37.],
       [ 50.,  52.],
       [ 65.,  67.]])

## Slicing and indexing with NumPy arrays

In [128]:
import numpy as np
M = np.arange(10*10, dtype=int).reshape(10,10)

In [129]:
M[2:9:2,:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [130]:
M[2:9:2,5:]

array([[25, 26, 27, 28, 29],
       [45, 46, 47, 48, 49],
       [65, 66, 67, 68, 69],
       [85, 86, 87, 88, 89]])

In [131]:
M[2:9:2,5::-1]

array([[25, 24, 23, 22, 21, 20],
       [45, 44, 43, 42, 41, 40],
       [65, 64, 63, 62, 61, 60],
       [85, 84, 83, 82, 81, 80]])

In [132]:
row_index = (M[:,0]>=20) & (M[:,0]<=80)
col_index = M[0,:]>=5
M[row_index,:][:,col_index]

array([[25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89]])

In [133]:
mask = (M>=20) & (M<=90) & ((M / 10.) % 1 >= 0.5)
M[mask]

array([25, 26, 27, 28, 29, 35, 36, 37, 38, 39, 45, 46, 47, 48, 49, 55, 56,
       57, 58, 59, 65, 66, 67, 68, 69, 75, 76, 77, 78, 79, 85, 86, 87, 88,
       89])

In [134]:
row_index = [1,1,2,7]
col_index = [0,2,4,8]

In [135]:
M[row_index,col_index]

array([10, 12, 24, 78])

In [136]:
M[row_index,:][:,col_index]

array([[10, 12, 14, 18],
       [10, 12, 14, 18],
       [20, 22, 24, 28],
       [70, 72, 74, 78]])

In [137]:
N = M[2:9:2,5:].copy()

### Stacking NumPy arrays

In [138]:
import numpy as np
dataset = np.arange(10*5).reshape(10,5)

In [139]:
single_line = np.arange(1*5).reshape(1,5)
a_few_lines = np.arange(3*5).reshape(3,5)

In [140]:
np.vstack((dataset,single_line))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4]])

In [141]:
np.vstack((dataset,a_few_lines))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [142]:
np.vstack((dataset,single_line,single_line))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4]])

In [143]:
bias = np.ones(10).reshape(10,1)
np.hstack((dataset,bias))

array([[  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.],
       [ 25.,  26.,  27.,  28.,  29.,   1.],
       [ 30.,  31.,  32.,  33.,  34.,   1.],
       [ 35.,  36.,  37.,  38.,  39.,   1.],
       [ 40.,  41.,  42.,  43.,  44.,   1.],
       [ 45.,  46.,  47.,  48.,  49.,   1.]])

In [144]:
bias = np.ones(10)
np.column_stack((dataset,bias))

array([[  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.],
       [ 25.,  26.,  27.,  28.,  29.,   1.],
       [ 30.,  31.,  32.,  33.,  34.,   1.],
       [ 35.,  36.,  37.,  38.,  39.,   1.],
       [ 40.,  41.,  42.,  43.,  44.,   1.],
       [ 45.,  46.,  47.,  48.,  49.,   1.]])

In [145]:
np.dstack((dataset*1,dataset*2,dataset*3))

array([[[  0,   0,   0],
        [  1,   2,   3],
        [  2,   4,   6],
        [  3,   6,   9],
        [  4,   8,  12]],

       [[  5,  10,  15],
        [  6,  12,  18],
        [  7,  14,  21],
        [  8,  16,  24],
        [  9,  18,  27]],

       [[ 10,  20,  30],
        [ 11,  22,  33],
        [ 12,  24,  36],
        [ 13,  26,  39],
        [ 14,  28,  42]],

       [[ 15,  30,  45],
        [ 16,  32,  48],
        [ 17,  34,  51],
        [ 18,  36,  54],
        [ 19,  38,  57]],

       [[ 20,  40,  60],
        [ 21,  42,  63],
        [ 22,  44,  66],
        [ 23,  46,  69],
        [ 24,  48,  72]],

       [[ 25,  50,  75],
        [ 26,  52,  78],
        [ 27,  54,  81],
        [ 28,  56,  84],
        [ 29,  58,  87]],

       [[ 30,  60,  90],
        [ 31,  62,  93],
        [ 32,  64,  96],
        [ 33,  66,  99],
        [ 34,  68, 102]],

       [[ 35,  70, 105],
        [ 36,  72, 108],
        [ 37,  74, 111],
        [ 38,  76, 114],
        [ 3

In [146]:
np.insert(dataset, 3, bias, axis=1)

array([[ 0,  1,  2,  1,  3,  4],
       [ 5,  6,  7,  1,  8,  9],
       [10, 11, 12,  1, 13, 14],
       [15, 16, 17,  1, 18, 19],
       [20, 21, 22,  1, 23, 24],
       [25, 26, 27,  1, 28, 29],
       [30, 31, 32,  1, 33, 34],
       [35, 36, 37,  1, 38, 39],
       [40, 41, 42,  1, 43, 44],
       [45, 46, 47,  1, 48, 49]])

In [147]:
np.insert(dataset, 3, dataset.T, axis=1)

array([[ 0,  1,  2,  0,  1,  2,  3,  4,  3,  4],
       [ 5,  6,  7,  5,  6,  7,  8,  9,  8,  9],
       [10, 11, 12, 10, 11, 12, 13, 14, 13, 14],
       [15, 16, 17, 15, 16, 17, 18, 19, 18, 19],
       [20, 21, 22, 20, 21, 22, 23, 24, 23, 24],
       [25, 26, 27, 25, 26, 27, 28, 29, 28, 29],
       [30, 31, 32, 30, 31, 32, 33, 34, 33, 34],
       [35, 36, 37, 35, 36, 37, 38, 39, 38, 39],
       [40, 41, 42, 40, 41, 42, 43, 44, 43, 44],
       [45, 46, 47, 45, 46, 47, 48, 49, 48, 49]])

In [148]:
np.insert(dataset, 3, np.ones(5), axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 1,  1,  1,  1,  1],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])